frequencies:
  allow_custom: true
  fm:
    min: 100.0
    max: 199.9
    step: 0.1
    default: 101.1
    chat_distance: 40.0
    max_count: 1000
  am:
    min: 1000
    max: 1999
    step: 1
    default: 1000
    chat_distance: 100.0
    max_count: 1000
  custom:
    Police:
      type: "FM"
      frequency: 123.0
      chat_distance: 60.0
    Emergency:
      type: "AM"
      frequency: 456
      chat_distance: 120.0

options:
  show_join_message: true
  show_disconnect_message: true
  enable_proximity: true
  max_message_length: 256
  cooldown_connect: 2
  cooldown_disconnect: 2
  enable_static: true
  static_threshold: 0.75
  static_intensity: 0.5
  enable_signal_bar: true
  signal_update_interval: 20
  enable_sounds: true
  sound_connect: "block.note_block.pling"
  sound_disconnect: "block.note_block.bass"
  sound_static: "entity.experience_orb.pickup"
  connect_cooldown_seconds: 5

advanced:
  debug_mode: false
